[profile.default]
src = "src"
out = "out"
test = "test"
script = "script"
libs = ["lib", "node_modules"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 1000000
via_ir = true

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
